### ISSUE TITLE
Require org-mode 8

### ISSUE THREAD

**Issue by drym3r** [dfeich/org-clock-convenience#4] opened 2017-09-07 13:02 UTC
Hi

First of all, thanks for your work!

This package requires org-mode 8 installed, which makes this version to be installed from melpa. It shouldn't happen. For example, I use org-mode from git and it install the melpa package anyway.

Thanks

**Comment by dfeich** [comment] 2017-09-26 06:16
Dear drym3r

I was on vacation for some weeks, so sorry for responding late. You are touching a real problem, and I do not know the solution right now. By best practice one needs to have the dependency inside the package. Now the question is why the package from git is not registering a "reasonable" version number. Can you tell me what your git-built org is delivering when you execute org-version?

Best regards,
Derek

**Comment by drym3r** [comment] 2017-09-30 17:30
No problem. I understand that it should have some version number, but I guess the package manager should be able to see that I'm already using a higher org-mode version.

I'm using the maint version:
```
Org mode version 9.0.9 (release_9.0.9-84-g731f59-git @ /home/drymer/.emacs.d/el-get/org-mode-maint/lisp/)
```

**Comment by dfeich** [comment] 2018-02-09 20:28
Closing. The dependencies are correctly stated in the module. The problem is probably in the way the package system is testing for the dependency of org mode and how the version number is obtained.
Sorry for not being able to offer a clean resolution to your problem.

**Closed as completed by dfeich** 2018-02-09 20:28 UTC
